apiVersion: v1
kind: Service
metadata:
  name: restaurent-website
  labels:
    app: restaurent-website
spec:
  type: NodePort
  selector:
    app: restaurent-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
